version: '3.1'


services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root 
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8585:8585