version: '3'

services:
    prometheus:
      image: prom/prometheus:v2.40.4
      ports:
        - 9090:9090
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
        - monitoring
      restart: unless-stopped
    grafana:
      image: grafana/grafana:9.3.0
      ports:
        - 3000:3000
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      networks:
        - monitoring
      volumes:
        - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
        - grafana:/var/lib/grafana
    app:
      build: 
        context: . 
        dockerfile: Dockerfile
      container_name: app 
      networks:
        - monitoring
      ports:
        - 8080:8080 
        - 8081:8081

volumes:
  prometheus_data:
  grafana:

networks:
  monitoring: