FROM golang as builder 
WORKDIR /gok8s 
COPY go.mod .  
COPY go.sum . 
RUN go mod download 
COPY . . 
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/gok8s .

FROM alpine:latest 
RUN apk --no-cache add ca-certificate 
RUN addgroup -S gok8s && adduser -S gok8s -G gok8s 
USER gok8s 
WORKDIR /home/gok8s 
COPY --from=builder /bin/gok8s ./
EXPOSE 4000 
ENTRYPOINT [ "./gok8s" ]