version: '3.8'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      - REDIS_ARGS="--requirepass redis-stack"
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./local-data/:/data


volumes:
  local-data:
  